export type LessonLevel = "BEG" | "INT" | "ADV";

export type Lesson = {
  id: number;
  module: string;
  moduleIndex: number;
  title: string;
  minutes: number;
  level: LessonLevel;
  hook: string;
  body: string;
  exercise: string;
  keyTakeaway: string;
};

export const MODULES = [
  "I. Foundations",
  "II. Everyday work",
  "III. Creation",
  "IV. Business workflows",
  "V. Industry deep dives",
  "VI. Building with AI",
] as const;

export const LESSONS: Lesson[] = [
  {
    id: 1, module: "I. Foundations", moduleIndex: 0, title: "When to use ChatGPT vs. Google", minutes: 5, level: "BEG",
    hook: "You've been using the wrong tool for half your questions. Here's the 10-second test that fixes that.",
    body: `Most people treat ChatGPT and Google as interchangeable. They're not. Getting this wrong costs you 20 minutes of bad results before you give up and switch anyway.\n\n**Google is for facts with a source you can verify.** Stock prices, news, what a regulation actually says. Google indexes the real world in near-real-time. ChatGPT doesn't. Its knowledge has a cutoff date and it can't check URLs.\n\n**ChatGPT is for tasks that require reasoning, synthesis, or generation.** Drafting an email. Explaining a concept in simpler terms. Restructuring a document. Brainstorming five angles on a problem. Anywhere you'd otherwise stare at a blank page.\n\nThe 10-second test: ask yourself "does this question have one correct answer that exists somewhere in the world?" If yes, Google. If the answer needs to be *created* or *reasoned through*, ChatGPT.\n\nWhere people go wrong: they ask ChatGPT for facts ("what's the current interest rate?") and get confident-sounding nonsense. Or they Google "how should I structure my performance review?" and get 14 generic listicles instead of something tailored to their situation.\n\nThere's a third category: **research synthesis**, which is where you use both. Google to find the primary sources. ChatGPT to help you understand, compare, and summarize them. That combination is genuinely powerful and most people never do it.`,
    exercise: "Your 5-minute exercise: Write down the last 5 things you Googled in the past two days. For each one, ask: was this a fact-lookup or a reasoning/creation task? How many could have been better served by ChatGPT? Pick one and try it now.",
    keyTakeaway: "Google retrieves; ChatGPT creates: when you mix them up, you get confident-sounding wrong answers or 14 listicles that say nothing.",
  },
  {
    id: 2, module: "I. Foundations", moduleIndex: 0, title: "Spot when AI is making things up", minutes: 5, level: "BEG",
    hook: "ChatGPT lies with complete confidence. And there are four tells that give it away every time.",
    body: `Hallucination isn't a bug they're going to fix next month. It's a structural feature of how language models work. They predict the most plausible-sounding next token, which means they'll invent a plausible-sounding answer even when the right answer is "I don't know."\n\n**The four hallucination tells:**\n\n**1. Suspiciously specific details.** "The study, published in the Journal of Applied Psychology in 2019, found that 73% of..." Invented citations are often precise in the wrong way. Always verify any citation before using it.\n\n**2. Confident claims about recent events.** Anything after the model's training cutoff is either fabricated or outdated. If it's telling you about something recent without hedging, it's guessing.\n\n**3. No hedging on genuinely uncertain territory.** Good models hedge: "I'm not certain, but..." Bad answers charge straight through uncertainty.\n\n**4. Internal contradictions.** Hallucinations often contradict themselves within the same response. Read the full answer before acting on it.\n\nThe fix isn't to stop using AI: it's to use it for the right things. Use it for synthesis and generation where "mostly right" is fine. Verify anything you'd stake your reputation on.`,
    exercise: "Your 5-minute exercise: Ask ChatGPT to 'list three academic studies on remote work productivity.' Then try to verify one: find the journal, the year, the authors. What did you find?",
    keyTakeaway: "Hallucinations are structural, not bugs. Train yourself to spot the four tells before you paste anything into a document with your name on it.",
  },
  {
    id: 3, module: "I. Foundations", moduleIndex: 0, title: "The 3-step framing technique", minutes: 7, level: "BEG",
    hook: "One extra sentence before your prompt doubles the quality of every answer you'll ever get.",
    body: `The difference between a mediocre prompt and a great one isn't length: it's framing. And framing has exactly three components.\n\n**Step 1: Role.** Tell the model who it's talking to. Not "pretend you're an expert". Tell it *your* context. "I'm a marketing manager at a 50-person SaaS company" shapes the vocabulary, level of detail, and assumptions the model makes.\n\n**Step 2: Task.** Be specific about the output you want, not just the topic. "Help me with my email" is a topic. "Write a 3-paragraph email to my manager explaining the Q3 delay, without making it sound like I'm making excuses, ending with a proposed solution" is a task.\n\n**Step 3: Constraints.** Tell it what *not* to do, what format you want, and what length. These are the instructions most people skip, and they're what separate a generic paragraph from something you can actually use.\n\nAssembled: **"I'm a [role]. I need [specific output]. Keep it [constraints]."**\n\nExample: "I'm a product manager at a fintech startup preparing for a board meeting. Write a 5-bullet executive summary of our Q3 results, focusing on user growth and revenue, in a tone that's confident but acknowledges we missed our retention target."\n\nThat's it. Three seconds of framing, 10x better output.`,
    exercise: "Your 5-minute exercise: Take a prompt you've used recently that gave you a mediocre result. Apply all three steps: role, specific task, constraints, and run it again. Compare the outputs side by side.",
    keyTakeaway: "Role + specific task + constraints: three seconds of framing changes the answer from generic to actually useful.",
  },
  {
    id: 4, module: "I. Foundations", moduleIndex: 0, title: "Stop writing prompts (start writing briefs)", minutes: 6, level: "BEG",
    hook: "Every bad AI output has the same root cause: you gave it a question when it needed a brief.",
    body: `A prompt is a question. A brief is a document. The distinction matters because ChatGPT isn't a search engine: it's a collaborator. And you wouldn't hand a collaborator a single sentence and expect professional output.\n\n**What a brief includes that a prompt doesn't:**\n\n**Context:** What's the situation? Who's the audience? What's already been decided? Adding "We're launching a B2B analytics feature to a list of 3,000 SMB customers who have been on our waitlist for 6 months" transforms a generic prompt into something the model can actually work with.\n\n**Stakes:** Why does this matter? What does success look like? When the model understands what you're trying to accomplish, it makes better tradeoffs.\n\n**Examples:** If you have a voice or a previous output you liked, paste it in. "Write in a tone similar to this: [paste]" is the fastest path to matching your style.\n\n**Rejection criteria:** What would make the output bad? "Don't use corporate jargon. Don't start with 'We're excited to announce.' Don't exceed 150 words." These constraints are as important as the instructions.\n\nThe transition from prompting to briefing is the single biggest skill shift in working with AI. It takes 60 more seconds and saves 20 minutes of revision.`,
    exercise: "Your 5-minute exercise: Write a brief (not a prompt) for the next work task on your to-do list. Include context, stakes, any style examples, and at least two rejection criteria. Run it and notice what's different.",
    keyTakeaway: "A brief takes 60 seconds longer to write than a prompt and saves 20 minutes of back-and-forth revisions.",
  },
  {
    id: 5, module: "I. Foundations", moduleIndex: 0, title: "Set up AI once so it remembers how you work", minutes: 8, level: "BEG",
    hook: "You've been setting up your AI from scratch every single conversation. There's a way to stop doing that.",
    body: `Every time you open a new ChatGPT conversation, you're starting from zero. The model doesn't know you're a product manager, doesn't know you prefer bullet points, doesn't know you're writing for a UK audience. That's why every first message has to re-establish context.\n\n**Custom instructions** (in ChatGPT) and **system prompts** (in Claude/API) solve this. They're persistent context injected before every conversation, essentially a permanent brief.\n\n**What to put in your custom instructions:**\n\n*Who you are:* "I'm a product manager at a Series B SaaS startup. My team is 8 people. My manager is non-technical."\n\n*How you want responses:* "Be direct. Skip preamble. Use bullet points for lists. If you're uncertain, say so explicitly."\n\n*Tone and style:* "I write in a conversational but professional tone. No buzzwords. No em-dashes used for emphasis."\n\n*Recurring context:* Anything you find yourself re-explaining frequently, such as your company's product, your audience, your constraints.\n\n**What not to put in:** Task-specific instructions. Custom instructions are for persistent identity, not one-off tasks.\n\nSetting this up takes 15 minutes once. It makes every subsequent conversation 30% better without any extra effort on your part.`,
    exercise: "Your 5-minute exercise: Open ChatGPT settings → 'Customize ChatGPT' (or Claude's profile settings). Write your custom instructions using the template above: who you are, how you want responses, your tone, and one piece of recurring context.",
    keyTakeaway: "Custom instructions are a one-time 15-minute investment that makes every future conversation 30% more useful. Set them up today.",
  },
  {
    id: 6, module: "II. Everyday work", moduleIndex: 1, title: "The 5-minute meeting debrief protocol", minutes: 5, level: "BEG",
    hook: "Most action items from meetings disappear within 48 hours. Here's a protocol that takes 5 minutes and captures everything.",
    body: `The problem with meetings isn't the meeting: it's what happens in the 15 minutes after. People scatter. Action items get buried. By the next day, everyone remembers the discussion but not the decisions.\n\n**The protocol:** Within 5 minutes of ending any meeting, open ChatGPT and paste or voice-type your rough notes. Use this prompt:\n\n*"I just had a [type of meeting] with [who]. Here are my rough notes: [paste]. Please: 1) Summarize the key decisions made, 2) List action items with owners if mentioned, 3) Flag any open questions that weren't resolved, 4) Draft a 3-sentence follow-up message I can send to the group."*\n\nThe output becomes your meeting record and your follow-up email draft in under 2 minutes.\n\n**Why rough notes work fine:** You don't need to clean up your notes before pasting: the model handles messy, stream-of-consciousness input well. Abbreviations, half-sentences, bullet fragments: all fine.\n\n**The voice shortcut:** On mobile, use voice-to-text to dictate your notes immediately after hanging up. The raw transcript feeds directly into the prompt. No typing, no cleanup.\n\nThis protocol works because it forces you to extract the cognitive value while the meeting is still fresh, but outsources the formatting and drafting to the model.`,
    exercise: "Your 5-minute exercise: After your next meeting, write 5-10 rough bullet points of what happened. Run them through the protocol above. How does the output compare to your usual post-meeting notes?",
    keyTakeaway: "Rough notes + a structured prompt immediately after the meeting captures everything and drafts the follow-up before you've even walked back to your desk.",
  },
  {
    id: 7, module: "II. Everyday work", moduleIndex: 1, title: "Inbox triage: auto-drafting responses", minutes: 6, level: "BEG",
    hook: "The emails that take you 20 minutes to draft take ChatGPT 30 seconds. And the difference in quality is smaller than you think.",
    body: `Most professional emails follow a handful of patterns: updates, requests, declines, follow-ups, introductions. Once you recognize the pattern, drafting becomes mostly structural, and structure is exactly what AI is good at.\n\n**The triage system:**\n\n**Tier 1: Auto-draft:** Routine emails (status updates, meeting confirmations, standard follow-ups). Paste the incoming email + your 2-3 bullet points of what you want to say. Prompt: *"Draft a professional reply to this email. My key points: [bullets]. Tone: [warm/direct/formal]. Max 150 words."*\n\n**Tier 2: Draft + edit:** Sensitive or relationship-important emails. Let the AI draft, but you edit substantively. Use it to get past the blank page, not to sign off without reading.\n\n**Tier 3: Write yourself:** Anything where the nuance is everything, a difficult conversation, a negotiation, something that will be forwarded or quoted.\n\nThe mistake people make is applying Tier 3 effort to Tier 1 emails. A meeting confirmation doesn't need your full creative attention.\n\n**The voice trick:** For Tier 1 emails, voice-dictate your thoughts in 30 seconds. That dictation becomes your brief.`,
    exercise: "Your 5-minute exercise: Find 3 emails in your drafts or inbox that you've been avoiding. Classify each as Tier 1, 2, or 3. Draft the Tier 1 ones using the auto-draft method above. Send at least one.",
    keyTakeaway: "Classify every email before you write it. 80% are Tier 1 and can be drafted in 30 seconds, saving your cognitive load for the 20% that actually need it.",
  },
  {
    id: 8, module: "II. Everyday work", moduleIndex: 1, title: "Writing better briefs for external teams", minutes: 7, level: "BEG",
    hook: "The reason external agencies and freelancers deliver the wrong thing isn't their fault: it's yours.",
    body: `A bad brief produces a bad deliverable. This is true for design agencies, copywriters, developers, and any external collaborator. The problem is that most people write briefs that describe what they want without explaining why they want it or what bad looks like.\n\n**The AI-assisted brief template:**\n\n1. **Background:** What's the context? What exists already?\n2. **Objective:** What does success look like in one measurable sentence?\n3. **Audience:** Who is this for? What do they know? What do they care about?\n4. **Deliverables:** Exact list of outputs with specs (format, length, deadline)\n5. **Constraints:** What's off-limits? What tone/style to avoid?\n6. **Examples:** Links or pastes of things you like (and briefly why)\n7. **Questions:** Things you need answered before work can start\n\nExplain your situation to ChatGPT and ask it to draft a brief using this structure. The model will produce a first draft in 60 seconds. You edit it. The resulting brief is 3x more detailed than what most people send, which means 3x fewer revision rounds.\n\n**The meta-benefit:** Writing the brief often reveals that you haven't made the decisions yet. Better to find out before the kickoff call than during the third revision.`,
    exercise: "Your 5-minute exercise: Pick an upcoming project with an external collaborator. Use ChatGPT to draft a brief using the 7-part template. Share it and note how the quality of the first questions back changes.",
    keyTakeaway: "A brief that explains the why and defines what bad looks like cuts revision rounds in half. AI drafts it in 60 seconds, you just need to fill in what you know.",
  },
  {
    id: 9, module: "II. Everyday work", moduleIndex: 1, title: "Calendar audits: where did your week go?", minutes: 5, level: "BEG",
    hook: "You probably have no idea where 40% of your working hours actually went last week.",
    body: `Most people estimate their time spent on different activities very inaccurately. They feel busy, they feel productive, but when they audit their calendar they find that meetings they thought took 30% of their week actually took 55%.\n\n**The audit:** Export or screenshot your last week's calendar. Paste the rough schedule into ChatGPT with this prompt:\n\n*"Here's my calendar for last week: [paste]. Please: 1) Categorize each block into: Meetings, Deep work, Admin, External calls, Unclear. 2) Calculate the approximate percentage of working time in each category. 3) Flag any patterns that might indicate time leaks. 4) Suggest three specific changes to next week's calendar."*\n\nThe output gives you a clear breakdown in 30 seconds that would take 20 minutes to do manually.\n\n**What to do with it:** You're not trying to optimize every minute. You're trying to see if your calendar reflects your actual priorities. If "deep work on the roadmap" is 80% of your stated priority but 15% of your actual calendar, that gap is the problem.\n\nRun this audit once a month. It takes 5 minutes and the patterns it reveals tend to be uncomfortable but actionable.`,
    exercise: "Your 5-minute exercise: Do the calendar audit for last week right now. Paste your schedule (rough is fine) and run the prompt above. What category surprised you most?",
    keyTakeaway: "A monthly 5-minute calendar audit reveals whether your time allocation matches your stated priorities. Most people find a 30–40% gap.",
  },
  {
    id: 10, module: "II. Everyday work", moduleIndex: 1, title: "The Slack summary rule", minutes: 5, level: "BEG",
    hook: "You're spending 45 minutes a day reading Slack threads that could be summarized in 90 seconds.",
    body: `Slack is a river, not a document. By the time you get to a thread that happened while you were in meetings, there are 40 messages, three topic changes, and two decisions buried somewhere in the middle.\n\n**The rule:** Never read a long Slack thread linearly. Copy and summarize.\n\nSelect all the messages in a thread, copy them, and paste into ChatGPT with: *"Summarize this Slack thread. What was discussed? What was decided? What action items or open questions remain? Keep it to bullet points, 5 max."*\n\nThis takes 15 seconds and gives you a better read of the thread than reading it yourself, because it surfaces the signal without the noise (the jokes, the "+1"s, the "sounds good" messages that make up 60% of most threads).\n\n**Channel-level summaries:** If you've been away for a day and need to catch up on a busy channel, copy the last N messages and run the same prompt.\n\n**The boundary:** This doesn't work for threads where you need to feel the emotional temperature of the conversation. For those, read. For everything else, summarize.\n\nThe rule works because it forces you to extract meaning rather than consume content.`,
    exercise: "Your 5-minute exercise: Find the longest Slack thread from the past 48 hours. Copy all the messages and run the summary prompt. How long would reading it have taken vs. the 15 seconds this took?",
    keyTakeaway: "Paste, summarize, act. Never read a long thread linearly again; the model extracts signal from noise faster than you can scroll.",
  },
  {
    id: 11, module: "III. Creation", moduleIndex: 2, title: "Structural editing: rewrite without losing voice", minutes: 8, level: "INT",
    hook: "The reason AI-edited text sounds generic isn't the AI: it's that you're asking it to rewrite instead of restructure.",
    body: `There's a critical difference between asking AI to *rewrite* something and asking it to *restructure* it. Rewriting replaces your words with the model's words. Restructuring keeps your language but reorganizes the logic, the flow, and the hierarchy.\n\n**The structural edit prompt:**\n*"I've written this [piece]. Don't rewrite the language: I want to keep my voice. Instead: 1) Tell me if the structure makes logical sense, 2) Identify where I've buried the lede, 3) Suggest a better order for the sections, 4) Flag any paragraphs that repeat an idea I already made. Keep my exact wording unless I specifically ask you to change it."*\n\nThis gives you editorial feedback without homogenizing your writing.\n\n**When to let it rewrite:** Sections you've already identified as weak. Not the whole piece. Say: "Paragraph 3 is clunky. Rewrite it in the same general voice as paragraph 1."\n\n**The voice preservation trick:** Before editing, paste a sample of writing you love (your own or someone else's). Say: "Keep edits consistent with this voice: [paste]." The model uses it as a style anchor.\n\n**What to watch for:** AI has a reflex toward parallel structure and clean transitions. These can smooth out the intentional roughness that makes writing interesting. Read the output critically before accepting.`,
    exercise: "Your 5-minute exercise: Take something you've written in the past month. Run the structural edit prompt above. Focus only on the structure feedback. Does it surface something you already half-knew wasn't working?",
    keyTakeaway: "Ask for structural feedback, not a rewrite. The model can tell you what's wrong without replacing your voice with its own.",
  },
  {
    id: 12, module: "III. Creation", moduleIndex: 2, title: "The brainstorming loop: getting past version 1", minutes: 7, level: "INT",
    hook: "Version 1 of anything is almost never good. And AI can get you to version 5 in the time it used to take to get to version 2.",
    body: `Brainstorming with AI works best when you treat it as an iterative loop rather than a single prompt. The first output is almost always too generic. The value comes from what you do with it next.\n\n**The loop:**\n\n**Round 1: Diverge:** Ask for 10 options, not 3. More options means more raw material. Prompt: "Give me 10 different angles on [problem]. Make them genuinely different from each other, not variations on the same theme."\n\n**Round 2: Interrogate:** Pick the 2-3 that have something interesting. Ask: "Why does option 7 work? What's the underlying insight? What would make it stronger?"\n\n**Round 3: Constrain:** Add a constraint that forces creativity. "Give me 5 more options, but each one has to be framed around [a constraint you haven't tried]."\n\n**Round 4: Combine:** "Take the tension from option 3 and the specificity from option 8 and create something new." Combination is often where the best ideas live.\n\nThe whole loop takes 15 minutes and produces something genuinely yours, because you made every curatorial decision. The AI generated the clay; you shaped it.`,
    exercise: "Your 5-minute exercise: Pick a problem you've been stuck on. Run all 4 rounds above, spending about 2 minutes per round. What did you arrive at that you didn't have going in?",
    keyTakeaway: "Run 4 rounds: diverge → interrogate → constrain → combine; the best idea is almost never in the first output.",
  },
  {
    id: 13, module: "III. Creation", moduleIndex: 2, title: "Make a great image from a sentence", minutes: 9, level: "INT",
    hook: "The difference between a mediocre AI image and a stunning one is entirely in the prompt. Here's the structure that works.",
    body: `Midjourney (and DALL-E, and Stable Diffusion) responds to prompts very differently from text models. Text models reward conversational clarity. Image models reward stacking of specific descriptors.\n\n**The image prompt formula:**\n[Subject] + [Context/setting] + [Lighting] + [Style/medium] + [Technical parameters]\n\nExample: "Product designer at a wooden desk, morning light from a large window, warm ambient, cinematic editorial photography, 35mm, shallow depth of field --ar 16:9 --v 6"\n\n**The five levers:**\n\n**Subject:** Be specific. "A woman" vs. "a 30s product manager looking frustrated at a laptop" produces different results.\n\n**Lighting:** This is the highest-leverage descriptor. "Golden hour," "overcast flat light," "dramatic rim lighting". Lighting changes the entire emotional register.\n\n**Style anchor:** Reference a known aesthetic. "Shot in the style of Magnum Photos," "Bauhaus design poster," "1970s editorial magazine spread."\n\n**Camera language:** "35mm lens," "f/1.4," "medium format," "bird's-eye view". These cue the model on composition.\n\n**Negative prompts:** Explicitly exclude things. "--no text, watermarks, extra limbs, oversaturated" clears the most common artifacts.\n\nStart with the formula, run it, then iterate on whichever lever produced the wrong output.`,
    exercise: "Your 5-minute exercise: Think of an image you need for work. Build a prompt using the formula above. Run it in DALL-E (free in ChatGPT). What do you need to change in round 2?",
    keyTakeaway: "Subject + setting + lighting + style anchor + technical parameters: stack these five and you'll get a usable image in 2–3 iterations instead of 15.",
  },
  {
    id: 14, module: "III. Creation", moduleIndex: 2, title: "Synthesizing research: 30 PDFs into 1 page", minutes: 10, level: "INT",
    hook: "The report that used to take two weeks of reading now takes two hours, if you know how to feed documents to a model.",
    body: `Research synthesis is one of the highest-value things AI can do for knowledge workers. But most people approach it wrong: they paste one document at a time and lose the cross-document threads that are the actual value.\n\n**The synthesis workflow:**\n\n**Step 1: Chunk strategically.** Group documents by theme or argument. Process related documents together so the model can surface agreements and contradictions.\n\n**Step 2: Extract before synthesizing.** For each chunk: *"What are the 3 most important claims in this document? What evidence does it use? What does it assume?"* Build an extraction document before asking for synthesis.\n\n**Step 3: Cross-document synthesis.** With your extractions: *"Here's what each document says about [topic]. Where do they agree? Where do they contradict? What question do they collectively fail to answer?"*\n\n**Step 4: The 1-pager.** *"Write a 1-page executive summary of the above synthesis. Structure: key finding, three supporting points, one major caveat, one open question."*\n\n**What the model can't do:** Evaluate the *quality* of sources or the credibility of methodology. That's your job. Use the model to handle volume; use your judgment to handle quality.`,
    exercise: "Your 5-minute exercise: Find 3 documents about the same topic. Run steps 1–3 above. What thread across all three did you miss when reading them individually?",
    keyTakeaway: "Extract first, synthesize second. The model finds cross-document patterns you'd miss reading them one at a time.",
  },
  {
    id: 15, module: "III. Creation", moduleIndex: 2, title: "The outline method for long-form content", minutes: 8, level: "INT",
    hook: "The blank page problem disappears the moment you separate structure from writing. Here's how.",
    body: `Long-form content fails at the outline stage 90% of the time. Either there's no outline (you're writing into the void) or the outline is too vague to be useful. The result is writing that meanders, repeats itself, and doesn't build toward anything.\n\n**The AI outline method:**\n\n**Phase 1: Brain dump.** Tell the model everything you know and think about the topic in 200 words of stream-of-consciousness. Don't edit. Don't organize. Just dump.\n\n**Phase 2: Structure extraction.** *"Based on my brain dump, give me 5 possible structural approaches. For each: a title, a 3-sentence description of the argument arc, and who it's best for."* Pick one.\n\n**Phase 3: Section breakdown.** *"Now break this into sections. For each section: a heading, 2-sentence summary of what it covers, and what the reader should feel or know by the end."*\n\n**Phase 4: Write section by section.** Now you're not writing a 2,000-word piece: you're writing 8 chunks of 250 words each, each with a clear purpose. That's a completely different and much easier task.\n\nThe outline is where you make the decisions. The writing is where you execute them.`,
    exercise: "Your 5-minute exercise: Pick a piece of content you've been avoiding. Do phases 1 and 2 above. Does having 5 structural options change how you think about the piece?",
    keyTakeaway: "Separate structure from writing. Let AI give you 5 structural options, pick one, then write section-by-section instead of into the void.",
  },
  {
    id: 16, module: "IV. Business workflows", moduleIndex: 3, title: "Automating lead research", minutes: 9, level: "INT",
    hook: "Your sales team is spending 40% of their time on research that could be done in 10 minutes per lead.",
    body: `Lead research before an outreach or discovery call typically involves: checking the company website, skimming the LinkedIn profile, reading recent news, and trying to find a hook. Manually, this takes 20–30 minutes per lead. With a structured AI workflow, it takes 8–10.\n\n**The lead research stack:**\n\n**Step 1: Context dump.** Paste what you know: the company name, the contact's LinkedIn bio, any recent news you found.\n\n**Step 2: Research prompt.** *"I'm preparing for an outreach to [contact] at [company]. Based on the context provided: 1) What are the likely pain points for someone in this role? 2) What business context should I know? 3) What are 3 potential hooks? 4) What one question would be most valuable to understand before this call?"*\n\n**Step 3: Personalization brief.** *"Now write a 3-sentence opening for an outreach email that references the most specific and relevant point above. Don't be generic."*\n\nThe full workflow takes 10 minutes per lead. At 20 leads/week, that's 3–4 hours saved, hours that go back into actual relationship-building.`,
    exercise: "Your 5-minute exercise: Pick a real prospect you're planning to reach out to. Run the 3-step research stack above. How does the output compare to what you'd have found in 20 minutes of manual research?",
    keyTakeaway: "Context dump + research prompt + personalization brief: 10 minutes of structured AI research outperforms 30 minutes of manual tab-switching.",
  },
  {
    id: 17, module: "IV. Business workflows", moduleIndex: 3, title: "Turn a screen recording into a step-by-step guide", minutes: 8, level: "INT",
    hook: "The knowledge that lives in people's heads is the most expensive operational risk your company has. Here's how to extract it.",
    body: `Standard Operating Procedures (SOPs) are one of the most valuable and most-neglected assets in any growing company. The bottleneck is always the same: creating them is tedious and time-consuming.\n\n**The video-to-SOP workflow:**\n\n**Step 1: Record a walkthrough.** Have the person who knows the process record a 10–15 minute screen recording + voice narration walking through exactly what they do. Loom is free.\n\n**Step 2: Transcribe.** Use a transcription tool (Whisper, Otter.ai, or ChatGPT's voice input) to convert the narration to text.\n\n**Step 3: SOP generation.** Paste the transcript: *"This is a transcription of a process walkthrough. Convert it into a step-by-step SOP with: 1) A one-sentence purpose statement, 2) Prerequisites, 3) Numbered steps with clear actions and expected outputs, 4) Common mistakes section, 5) A checklist at the end."*\n\n**Step 4: Review and verify.** Have the original person read the draft SOP and catch anything wrong or missing. This takes 10 minutes, not the 2 hours writing from scratch would have taken.\n\nThe bottleneck shifts from "writing it" to "recording it." Recording is fast because people can speak their process naturally.`,
    exercise: "Your 5-minute exercise: Record a 5-minute Loom of any repetitive process you do regularly. Run it through a transcriber and paste the transcript into the SOP prompt above. Is the output usable?",
    keyTakeaway: "Record → transcribe → prompt: converts a spoken walkthrough into a structured SOP in 30 minutes, replacing what used to take a full day.",
  },
  {
    id: 18, module: "IV. Business workflows", moduleIndex: 3, title: "Data cleaning for the spreadsheet-phobic", minutes: 10, level: "INT",
    hook: "You don't need to know Excel formulas if you can describe what you want in plain English.",
    body: `Data cleaning (removing duplicates, standardizing formats, filling gaps, reshaping tables) is the part of analytics work that takes the most time and delivers the least insight. It's also the part AI handles remarkably well.\n\n**The plain English approach:**\n\nInstead of learning VLOOKUP or writing Python, describe what you want. Paste a sample of your data (10–20 rows is enough) and explain the problem:\n\n*"I have a CSV with customer names in inconsistent formats (some 'First Last', some 'Last, First'). I need them all as 'First Last'. Here's a sample: [paste]. Give me: 1) An Excel formula to standardize column A, 2) A Python pandas snippet for batch processing, 3) A list of rows I need to manually review."*\n\n**What this handles well:**\n- Format standardization (dates, phone numbers, names)\n- Duplicate detection logic\n- Missing value imputation rules\n- Table reshaping (wide to long, long to wide)\n\n**What to verify:** Always spot-check 10 random rows after running any AI-generated formula. Edge cases (unusual characters, empty cells) can produce unexpected results.\n\nYou don't need to become a data analyst. You need to describe your data problem clearly.`,
    exercise: "Your 5-minute exercise: Find a messy spreadsheet. Pick one specific cleaning problem. Paste a sample and run the prompt above. Does it solve the problem?",
    keyTakeaway: "Describe the data problem in plain English with a sample. You don't need formulas when you can tell the model exactly what the data should look like.",
  },
  {
    id: 19, module: "IV. Business workflows", moduleIndex: 3, title: "Build your own AI helper that knows your company", minutes: 12, level: "INT",
    hook: "Your company has context that no public AI knows. Here's how to build a version that does.",
    body: `The frustration with generic AI outputs often comes from the model not knowing your company's specific context: your product, your customers, your voice, your internal terminology. Custom GPTs (or Claude Projects) solve this by letting you inject persistent context that applies to every conversation.\n\n**What to include in a custom GPT for your team:**\n\n**Company context:** What does your company do? Who are your customers? What are the names of your products/features?\n\n**Voice and tone guide:** How does your company communicate? Any words to avoid? Any phrases that are distinctly yours? Paste 3–5 examples of writing you love.\n\n**Common task templates:** Your most frequent workflows: the meeting debrief format, the weekly update structure, the customer email template. Define these as named tasks: "When I say 'debrief mode', use this format..."\n\n**Reference documents:** FAQs, pricing tables, product specs, anything the model might need to answer common questions accurately.\n\n**Building it:** In ChatGPT, go to "Explore GPTs" → "Create." In Claude, use "Projects." The setup takes 30–60 minutes once, and every team member can then use it.`,
    exercise: "Your 5-minute exercise: Write the first draft of a system prompt for a custom GPT for your team. Start with: what the company does, 3 voice guidelines, and one common task template.",
    keyTakeaway: "A custom GPT with your company context in the system prompt turns generic outputs into answers that actually fit your specific situation.",
  },
  {
    id: 20, module: "IV. Business workflows", moduleIndex: 3, title: "Competitor tracking on autopilot", minutes: 11, level: "INT",
    hook: "Your competitors are moving and you're finding out two months late. Here's the monitoring stack that costs nothing.",
    body: `Competitive intelligence is one of those things everyone agrees is important and almost no one does consistently. The problem is collection: someone has to go check all the sources on some cadence, and that person usually stops after two weeks.\n\n**The monitoring stack:**\n\n**Tier 1: Free, automated:**\n- Google Alerts for competitor names + key terms\n- LinkedIn notifications on competitor company pages\n- RSS feeds for their blog (Feedly, free tier)\n\n**Tier 2: Weekly synthesis:**\nOnce per week, dump any alerts/posts/news into ChatGPT: *"Here are updates from my competitors this week: [paste]. Summarize: 1) Any product changes, 2) Any positioning shifts, 3) Any strategy signals, 4) One implication for us."*\n\n**Tier 3: Quarterly deep dive:**\nEvery quarter, give ChatGPT each competitor's current homepage copy, pricing page, and job postings: *"Compare these competitors across: positioning, target customer, price point, growth signals. What gaps are they leaving that we could own?"*\n\nThe stack requires setup once and 20 minutes weekly. Most teams track competitors 0 hours per week until they're surprised.`,
    exercise: "Your 5-minute exercise: Set up Google Alerts for your two main competitors right now. While you're there, write one sentence describing each competitor's current positioning.",
    keyTakeaway: "Automate collection, synthesize weekly, deep-dive quarterly. Competitive intelligence doesn't need to be expensive, just consistent.",
  },
  {
    id: 21, module: "V. Industry deep dives", moduleIndex: 4, title: "AI in Product Management: spec writing", minutes: 8, level: "ADV",
    hook: "The PRD that used to take a PM two days to write now takes two hours: if you know which parts to delegate.",
    body: `Product specs (PRDs, feature briefs, technical requirements) are the highest-leverage documents a PM writes. They're also the most time-consuming. The good news: they're almost entirely structured, which makes them excellent candidates for AI assistance.\n\n**The spec writing workflow:**\n\n**Step 1: Problem statement.** Write this yourself. AI is bad at identifying problems; it's good at everything that comes after. Your 3-sentence problem statement should describe: who has the problem, what they currently do, and what makes that inadequate.\n\n**Step 2: AI-assisted scaffolding.** *"I'm writing a PRD for [feature]. The problem: [your statement]. Generate: 1) 3 user stories, 2) A draft success metrics section, 3) Potential edge cases, 4) A list of dependencies."*\n\n**Step 3: Scope definition.** *"What's the minimum viable version? What am I including that could be cut for v1? What would make this scope creep?"*\n\n**Step 4: Review checklist.** *"What critical sections are typically in a PRD that aren't yet in this draft?"*\n\nThe judgment calls stay with you. The scaffolding, structure, and completeness checks become fast.`,
    exercise: "Your 5-minute exercise: Think of the last feature you were involved in specifying. Run step 2 above for it. Does the model surface edge cases that weren't in the original spec?",
    keyTakeaway: "Write the problem statement yourself, delegate the scaffolding. AI is excellent at structure and edge-case generation, terrible at identifying the actual problem.",
  },
  {
    id: 22, module: "V. Industry deep dives", moduleIndex: 4, title: "AI in Marketing: campaign drafting", minutes: 8, level: "ADV",
    hook: "Marketing teams that still write every asset from scratch are losing to competitors running 10x the copy variations.",
    body: `Marketing is the function where AI has the most immediate, measurable impact. The reason is simple: marketing is about volume plus quality. And AI allows you to hit quality at volume for the first time.\n\n**The campaign drafting system:**\n\n**Positioning brief first:** Before touching AI, write: target audience (1 specific person), primary pain point (1 sentence), your solution (1 sentence), key proof point (1 statistic). This takes 10 minutes and makes everything downstream 5x better.\n\n**Copy variants:** *"I'm running a campaign targeting [audience] with this positioning: [brief]. Write: 3 subject lines, 3 headline variants, 2 full email body versions, 5 CTA button options. Each should feel genuinely different."*\n\n**Channel adaptation:** *"Take the winning headline. Adapt it for: a LinkedIn post (150 words), a Twitter opener, a paid ad headline (under 40 characters)."*\n\n**Iteration signal:** When you run A/B tests, feed results back: *"Version A won with 34% higher open rate. Why might X have won? Give me 5 more headline variations that push further in that direction."*\n\nThis isn't replacing your creative judgment: it's removing the blank page problem across every channel simultaneously.`,
    exercise: "Your 5-minute exercise: Write a 4-sentence positioning brief for any current campaign. Run the copy variants prompt. Pick the strongest 3 and note why they work.",
    keyTakeaway: "Positioning brief first, then copy at volume. Your job shifts from writing every word to making the curatorial decisions machines can't.",
  },
  {
    id: 23, module: "V. Industry deep dives", moduleIndex: 4, title: "AI in Design: copy-fitting and UX writing", minutes: 9, level: "ADV",
    hook: "UI copy is often treated as an afterthought, which is why most products sound like error message generators.",
    body: `UX writing (the words inside product interfaces) is disproportionately impactful and disproportionately neglected. Button labels, error messages, empty states, onboarding copy: these are often written in 10 minutes by the engineer who built the component.\n\n**AI for UX writing:**\n\n**Tone system prompt:** *"You are a UX writer for [product]. Our voice is [3 adjectives]. We speak to [audience]. We never use [banned phrases]. Use these principles for every output."*\n\n**Copy-fitting:** When space is constrained: *"I need this copy to fit in 32 characters: '[current copy]'. The message must convey [key meaning]. Give me 5 options."*\n\n**Error messages:** *"Write 3 options for an error message when a user's payment fails. Each should: say what happened in plain language, tell them what to do next, and not make them feel stupid. Under 2 lines."*\n\n**Empty states:** *"Write copy for an empty state when a user first lands on their dashboard with no data. Should be friendly, explain what they'll see here, and give one clear action."*\n\n**Consistency audit:** *"Here are all the button labels from our product: [paste]. Flag any that are inconsistent in verb tense, length, or formality."*\n\nGood UX copy is invisible when it's right and painful when it's wrong.`,
    exercise: "Your 5-minute exercise: Find 5 UI strings in a product you use or work on. Run them through the consistency audit prompt. How many fail the check?",
    keyTakeaway: "Set the tone system prompt once, then use AI to generate, fit, and audit UX copy. The model is faster at 32-character constraints than any human.",
  },
  {
    id: 24, module: "V. Industry deep dives", moduleIndex: 4, title: "AI in Operations: process mapping", minutes: 10, level: "ADV",
    hook: "Every operations problem is really a documentation problem. And documentation is exactly what AI is built for.",
    body: `Operations teams live and die by process clarity. A process that lives in someone's head is a process that breaks when that person is on vacation. Process mapping (making the implicit explicit) is tedious, which is why it doesn't happen until something breaks.\n\n**The AI-assisted process mapping workflow:**\n\n**Step 1: Interview capture.** Have a 20-minute conversation with the process owner. Ask: "Walk me through every step, including everything you consider obvious." Record and transcribe.\n\n**Step 2: Initial map generation.** *"Here's a transcription describing [process]. Generate: 1) A numbered step-by-step map, 2) A swimlane description (who does what in which system), 3) A list of decision points, 4) Dependencies."*\n\n**Step 3: Gap identification.** *"Given this process map, what are: 1) Single points of failure, 2) Steps lacking a clear owner, 3) Likely bottlenecks, 4) Steps that could be automated?"*\n\n**Step 4: Automation candidates.** For flagged steps: *"What tools or integrations could eliminate the manual work here? What would the integration look like?"*\n\nOperations improvement starts with seeing the process clearly. Most teams can't do that until it's on paper.`,
    exercise: "Your 5-minute exercise: Pick one recurring process. Spend 3 minutes writing every step you can think of, including the 'obvious' ones. Run step 2 above. What did you miss?",
    keyTakeaway: "Capture the process in conversation, map it with AI, then ask where it breaks. You can't fix what isn't visible.",
  },
  {
    id: 25, module: "V. Industry deep dives", moduleIndex: 4, title: "AI in Finance: quick P&L analysis", minutes: 10, level: "ADV",
    hook: "Most finance reports get read once, skimmed, and filed. Here's how to make them actually drive decisions.",
    body: `Financial reports exist to drive decisions, but most P&L analyses are produced in a format that doesn't support decision-making: dense tables, percentage changes with no context, and a narrative section that restates the numbers instead of explaining what to do about them.\n\n**The AI-assisted P&L analysis workflow:**\n\n**Step 1: Anonymize and paste.** Take your P&L data (replace sensitive figures with placeholders if needed). Paste it in table format.\n\n**Step 2: Plain language summary.** *"Here's a P&L for [period]. Write a 5-sentence plain-language summary of: the overall health signal, the two biggest contributors to performance, any unusual line items, and the trend direction."*\n\n**Step 3: Variance analysis.** *"Compare period A to period B. For each significant variance: suggest 2–3 possible explanations, note whether this is likely signal or noise, and suggest one clarifying question."*\n\n**Step 4: Decision framing.** *"Based on this P&L, what are the 3 most important financial decisions leadership should be discussing in the next 30 days? Frame each as a question, not a recommendation."*\n\nThe model won't know your company-specific context, so the output always requires your interpretation. But it structures the questions in ways that make board prep much faster.`,
    exercise: "Your 5-minute exercise: Find a public company's quarterly earnings release. Run step 2 and step 4 above. How does the AI framing compare to how the report was originally presented?",
    keyTakeaway: "Use AI to translate numbers into decisions. The model is excellent at surfacing patterns and framing questions, which is what P&L analysis should produce.",
  },
  {
    id: 26, module: "VI. Building with AI", moduleIndex: 5, title: "Connect AI to your other tools (no code)", minutes: 12, level: "ADV",
    hook: "You don't need to be a developer to call an API: you just need to understand what an API call actually is.",
    body: `An API (Application Programming Interface) is a way for one piece of software to talk to another. An LLM API is a way to send text to a model and get text back programmatically, without a web interface, in a way you control and can automate.\n\n**The mental model:** Think of an API call as a very formal version of opening ChatGPT and typing a message. You send: a system prompt (permanent instructions), a user message (the actual input), and some parameters (how creative/focused the response should be). You receive: the model's response as text your code can use.\n\n**Why this matters for non-coders:** Once you can make an API call, you can: automate repetitive prompting tasks, connect AI to your own data, build simple tools for your team, and stop being dependent on whoever manages the ChatGPT account.\n\n**Getting started (no coding required):**\n1. Get an API key from OpenAI or Anthropic (takes 2 minutes, costs a few cents per call)\n2. Use Make.com, Zapier, or n8n, visual interfaces that let you make API calls without writing code\n3. Start with one simple automation: "whenever I receive an email with [trigger], send it to the API with this prompt, and [do something with the output]"\n\n**The one concept to understand:** Tokens. API calls are priced by tokens (roughly 4 characters = 1 token). A short email costs $0.001. This is not expensive.`,
    exercise: "Your 5-minute exercise: Go to platform.openai.com or console.anthropic.com and create an API key. Open the API playground and make one test call using the visual interface. What did the call cost?",
    keyTakeaway: "An API call is just a structured message to a model. Once you understand that, the whole world of automation opens up without requiring coding skills.",
  },
  {
    id: 27, module: "VI. Building with AI", moduleIndex: 5, title: "Chain AI steps to finish a whole task", minutes: 15, level: "ADV",
    hook: "The most powerful AI workflows don't involve one model doing one thing: they involve models checking each other's work.",
    body: `A multi-agent loop is a workflow where the output of one AI call becomes the input to another. Instead of asking one model to write, edit, and fact-check in one pass, you have three separate passes that specialize.\n\n**A simple multi-agent loop: research → draft → critique**\n\n**Agent 1: Researcher:** *"Your job is to research and outline, not to write prose. Given [topic], produce: key facts, 3 competing viewpoints, and a recommended structure."*\n\n**Agent 2: Writer:** Feed Agent 1's output as context: *"You are a writer. Using only the research provided, write [piece]. Focus entirely on clarity and voice."*\n\n**Agent 3: Critic:** Feed Agent 2's output: *"You are an editor. Read the draft critically. Where is the logic weak? What would make a skeptical reader object? Suggest 3 specific improvements."*\n\n**Loop back:** Take the critique back to Agent 2: *"Given this critique, rewrite sections 2 and 3."*\n\n**No-code tools for this:** Make.com and n8n both support chained AI calls with variable passing. You can build this loop visually in 30 minutes.\n\nThe quality improvement over single-pass generation is substantial, and the critique step especially surfaces things even skilled human reviewers often miss.`,
    exercise: "Your 5-minute exercise: Run the 3-agent loop above manually using ChatGPT tabs (one per agent). Use a piece of content you're working on. How does Agent 3's critique compare to what you would have caught yourself?",
    keyTakeaway: "Specialist agents checking each other's work consistently outperform one generalist agent doing everything. The critique loop is the most powerful pattern in practical AI.",
  },
  {
    id: 28, module: "VI. Building with AI", moduleIndex: 5, title: "Pull data from any website without code", minutes: 11, level: "ADV",
    hook: "The data you need is publicly available on the web. And you don't need Python to get it.",
    body: `Web scraping sounds like a developer task. It's increasingly not. Several no-code tools make it possible to extract structured data from websites without writing code, and AI makes the extracted data useful.\n\n**The no-code scraping stack:**\n\n**Browse AI (browse.ai):** Point it at a URL, highlight what you want to extract (job titles, product prices, company names), and it builds a scraper you can run on a schedule. The free tier handles most research use cases.\n\n**Clay (clay.com):** Better for enriching lists. Give it a list of companies or people; it scrapes LinkedIn, websites, and other sources to add context.\n\n**ChatGPT with Web browsing:** For one-off scraping, paste a URL and ask for specific information. Not for large-scale, but useful for quick extractions.\n\n**What to do with the data:** Once you have structured data, the AI workflows from earlier modules kick in. "Here's a list of 50 job postings from Competitor X over 6 months. What are they building?" That's competitive intelligence that would otherwise take hours.\n\n**Legal note:** Always check a site's robots.txt and Terms of Service before scraping. Public data ≠ permitted to scrape.`,
    exercise: "Your 5-minute exercise: Go to browse.ai and extract a list from any public website. What does the structured output look like? What could you do with it?",
    keyTakeaway: "No-code scrapers + AI synthesis = competitive intelligence that used to require a data team, now available to any analyst with 30 minutes.",
  },
  {
    id: 29, module: "VI. Building with AI", moduleIndex: 5, title: "Find anything you've ever saved, instantly", minutes: 14, level: "ADV",
    hook: "You've written thousands of documents, taken thousands of notes, and read thousands of articles. Almost none of it is retrievable when you need it.",
    body: `Knowledge workers have a retrieval problem. We produce enormous volumes of notes, highlights, saved articles, meeting summaries, and documents. We can search within each tool. But we can't search *across* them, and we can't ask natural language questions of our own body of knowledge.\n\n**The personal knowledge base (PKB) stack:**\n\n**Step 1: Centralize input:** Pick one place where everything flows in. Notion (most flexible), Obsidian (most powerful for linking), or Roam (most opinionated). The right answer is the one you'll actually maintain.\n\n**Step 2: Add AI retrieval:**\n- **NotebookLM (Google, free):** Upload PDFs, docs, notes. Ask questions, get answers with citations.\n- **Mem.ai:** Takes notes and resurfaces them contextually, with AI synthesis.\n\n**Step 3: Capture habit:** A PKB is only as good as what goes into it. The sustainable minimum: one capture per day. Consistency beats completeness.\n\n**Step 4: Query it:** Once populated, ask questions you couldn't ask before: "What did I think about remote work 2 years ago?", "What notes do I have about pricing strategy?", "What was the argument in that article about decision-making?"\n\nThis is your second brain, queryable.`,
    exercise: "Your 5-minute exercise: Upload 5 documents to NotebookLM. Ask it 3 questions that require synthesizing across all 5. What did it surface that you'd forgotten?",
    keyTakeaway: "Centralize → enrich with AI retrieval → capture consistently. A searchable body of your own knowledge is the most underrated productivity investment.",
  },
  {
    id: 30, module: "VI. Building with AI", moduleIndex: 5, title: "The autonomous workday: what's next?", minutes: 12, level: "ADV",
    hook: "Everything in this course has been about augmenting what you do. What comes next is about what you no longer need to do at all.",
    body: `We've spent 29 lessons building AI fluency: using models to draft, synthesize, research, analyze, and create. That's the first era of working with AI. The second era, already beginning for early adopters, is autonomous agents: systems that operate continuously, make decisions, and take actions without requiring your input for every step.\n\n**What's already possible:**\n- Email triage agents that prioritize, draft, and send routine responses based on rules you define\n- Research agents that monitor sources and deliver briefings without being asked\n- Content pipelines that generate, review, and schedule without a human in the loop\n- Customer service agents that handle tier-1 issues and escalate only edge cases\n\n**What the threshold moment looks like for you:** It's the day you realize you spent an hour on work that ran automatically in the background. And the quality was good enough that you approved it without changes.\n\n**How to prepare:**\n1. **Document your decision rules.** The processes you've made explicit are the candidates for automation. Agents can follow rules; they can't infer undocumented preferences.\n2. **Build tolerance for imperfect outputs.** The comparison isn't "agent vs. perfection": it's "agent + your review vs. you doing it manually."\n3. **Start small and high-frequency.** Automate recurring low-stakes tasks first.\n\nThe 5 minutes you've invested each day for 30 days isn't about individual productivity tricks. It's about building the mental model to navigate a decade of change.`,
    exercise: "Your final exercise: Write down 3 recurring tasks in your workday that follow clear, documentable rules. For each, write the rules as if you were briefing an agent. These are your automation roadmap for the next 6 months.",
    keyTakeaway: "Document your decision rules now. The processes you've made explicit are the ones that become autonomous, and the ones still in your head will remain manual.",
  },
];

export function getLessonById(id: number): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}

export function getLessonsByModule(moduleIndex: number): Lesson[] {
  return LESSONS.filter((l) => l.moduleIndex === moduleIndex);
}

export function getNextLesson(currentId: number): Lesson | undefined {
  return LESSONS.find((l) => l.id === currentId + 1);
}

export function getPrevLesson(currentId: number): Lesson | undefined {
  return LESSONS.find((l) => l.id === currentId - 1);
}
