-- ─────────────────────────────────────────────────────────────────────────────
-- Seed: First Steps module mastery check. Generated by
-- scripts/gen-first-steps-check.mjs. Deterministic uuid v5 ids + ON CONFLICT
-- upserts, content only. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

begin;

insert into mastery_checks
  (id, slug, scope, lesson_id, module_id, level, title, description, question_count, pass_threshold, cooldown_hours, status) values
  ($lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, $lum$first-steps-module-check$lum$, $lum$module$lum$, NULL, $lum$29b588fb-3344-5efd-97f4-813d16bc9ea3$lum$::uuid, NULL, $lum$First steps: test out$lum$, $lum$Already get a real win in your first session, frame a request well, steer a draft, and paste safely? Pass this and the whole First Steps module leaves your path, marked complete.$lum$, 8, 0.8, 24, 'published')
on conflict (slug) do update set
  scope = excluded.scope,
  lesson_id = excluded.lesson_id,
  module_id = excluded.module_id,
  level = excluded.level,
  title = excluded.title,
  description = excluded.description,
  question_count = excluded.question_count,
  pass_threshold = excluded.pass_threshold,
  cooldown_hours = excluded.cooldown_hours,
  status = excluded.status;

insert into mastery_check_questions
  (id, check_id, order_index, type, content, source_block_id) values
  ($lum$b1a21dee-98be-5a69-b10f-3b19992fe89e$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 0, $lum$multiple_choice$lum$, $lum${"stem":"You open an AI tool for the very first time. What is the best way to spend your first five minutes?","options":[{"id":"a","label":"Quiz it with trivia and ask it for a joke to see how clever it is","is_correct":false,"explanation":"Testing it with trivia teaches you nothing about how it helps you. The win comes from real work."},{"id":"b","label":"Pick one small, real task from your day and use AI to actually finish it","is_correct":true,"explanation":"One small win on real work is what turns AI from a curiosity into a habit."},{"id":"c","label":"Read through every settings menu before you type anything","is_correct":false,"explanation":"You learn by doing a real task, not by studying menus first."}]}$lum$::jsonb, NULL),
  ($lum$1b8be930-e4a7-572f-95db-7ada45a24a41$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 1, $lum$multiple_choice$lum$, $lum${"stem":"Which of these is the kind of task AI handles best?","options":[{"id":"a","label":"Recalling the exact revenue figure for a company last quarter","is_correct":false,"explanation":"Specific facts and figures are a red-light task. AI sounds certain and may be wrong, so verify at the source."},{"id":"b","label":"Turning your rough notes into a clean first-draft summary","is_correct":true,"explanation":"Reshaping text you provide is AI's single strongest skill: you are the editor, it is the drafter."},{"id":"c","label":"Doing the precise math on your quarterly budget","is_correct":false,"explanation":"Math and precise calculations are a red-light task. Use a calculator or spreadsheet."}]}$lum$::jsonb, NULL),
  ($lum$ed8d6163-bb26-5eb7-a22b-4284be49e7c6$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 2, $lum$multiple_choice$lum$, $lum${"stem":"The AI's first answer is close but too formal. What do skilled users do?","options":[{"id":"a","label":"Open a brand-new prompt and start over from scratch","is_correct":false,"explanation":"Restarting throws away what worked. The chat already remembers the context."},{"id":"b","label":"Reply in the same chat, naming what is off and the one change they want, like 'good start, make it warmer'","is_correct":true,"explanation":"That is the iteration loop: keep what works, fix one thing, and the answer converges."},{"id":"c","label":"Accept it as final, since the first answer is usually the best one","is_correct":false,"explanation":"The first answer is round one, not a verdict. Steering it gets you far better results."}]}$lum$::jsonb, NULL),
  ($lum$3c960c90-9fe5-58b5-86d5-23e9d3cce4c8$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 3, $lum$multiple_choice$lum$, $lum${"stem":"Before pasting real text into a public AI tool, what is the core habit this module teaches?","options":[{"id":"a","label":"Memorize the privacy regulations for your industry first","is_correct":false,"explanation":"You do not need to memorize regulations. You need one quick reflex before pasting."},{"id":"b","label":"Pause a few seconds and ask whether the text could identify a real person, breach a confidence, or cause harm if it leaked","is_correct":true,"explanation":"That five-second check is the whole skill. If any answer is yes, strip the details or do not paste."},{"id":"c","label":"Tell the AI to keep your input confidential before you paste it","is_correct":false,"explanation":"An instruction does not control the service's data policy. The data is still exposed."}]}$lum$::jsonb, NULL),
  ($lum$b2ec8b25-ce1d-5d40-894c-71e124e7e743$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 4, $lum$multiple_choice$lum$, $lum${"stem":"What most reliably turns a generic AI answer into a useful one?","options":[{"id":"a","label":"Making the prompt as long as you possibly can","is_correct":false,"explanation":"It is not about length. It is about framing: who you are, what you want, and the limits."},{"id":"b","label":"Giving it your role, the specific output you want, and clear constraints","is_correct":true,"explanation":"Role plus a specific task plus constraints is the three-part frame that lifts answer quality."},{"id":"c","label":"Asking the same question several times until it improves on its own","is_correct":false,"explanation":"Repeating an unchanged question adds no new context, so the answer does not improve."}]}$lum$::jsonb, NULL),
  ($lum$23b1b171-2ee4-5bc9-8355-0c7efe40deff$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 5, $lum$multiple_choice$lum$, $lum${"stem":"You ask a simple question and get back six dense paragraphs you will not read. What is the fix?","options":[{"id":"a","label":"Accept that AI answers are always long and skim for the useful part","is_correct":false,"explanation":"Skimming is exactly how wrong details slip past. You can control the length."},{"id":"b","label":"Add a limit and a shape, like 'one sentence, then two bullets, under 60 words'","is_correct":true,"explanation":"The default is comprehensive, so you have to ask for brief and name the format you want."},{"id":"c","label":"Upgrade to a paid plan to get shorter answers","is_correct":false,"explanation":"Length is controlled by your instruction, not by the plan you are on."}]}$lum$::jsonb, NULL),
  ($lum$34d57680-187b-5142-8ee6-bc6288dd8f7c$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 6, $lum$fill_blank$lum$, $lum${"template":"When an AI states something false with total confidence, that is called a {{1}}, and it is the reason you {{2}} important facts at the source.","blanks":[{"id":"1","accept":["hallucination","hallucinations"],"ideal":"hallucination"},{"id":"2","accept":["verify","check","confirm"],"ideal":"verify"}],"explanation":"Hallucination is a side effect of how the model works, which is why you confirm anything that matters."}$lum$::jsonb, NULL),
  ($lum$5fc58090-ea08-5d1a-92df-cee3a485cf72$lum$::uuid, $lum$636013ec-6f12-5525-9a65-56b64e8ceb3e$lum$::uuid, 7, $lum$fill_blank$lum$, $lum${"template":"Setting up {{1}} instructions once means the AI remembers who you are and how you like responses, so you stop re-explaining your context in every new chat.","blanks":[{"id":"1","accept":["custom"],"ideal":"custom"}],"explanation":"Custom instructions are a one-time setup that makes every later conversation more useful."}$lum$::jsonb, NULL)
on conflict (id) do update set
  check_id = excluded.check_id,
  order_index = excluded.order_index,
  type = excluded.type,
  content = excluded.content,
  source_block_id = excluded.source_block_id;

commit;
